[project]
name = "nomadically-work-cleanup-jobs"
version = "0.1.0"
description = "Cloudflare Python Worker to clean up jobs older than 30 days"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "webtypy>=0.1.7",
]

[dependency-groups]
dev = [
    "workers-py",
    "workers-runtime-sdk",
]
